import { useTypewriterSlot } from "../hooks/useTypewriter";
import { TypewriterText } from "./TypewriterText";

const SOLANA_ADDRESS = "C2LJGNAGb2ZBD81rcHS7PtmFyuKWbJrJHxKyXHwUwZ7a";
const NOTE = "addresses generated by me. i hold the keys. nothing here has been earned yet.";

export function Support() {
  const noteSlot = useTypewriterSlot("support", 0, 1);

  return (
    <section>
      <div className="section-label">
        <span>support</span>
      </div>
      <div className="cell" style={{ wordBreak: "break-all" }}>
        <div className="muted" style={{ fontSize: 14, marginBottom: 4 }}>
          solana
        </div>
        <div>{SOLANA_ADDRESS}</div>
      </div>
      <p className="muted" style={{ fontSize: 14, marginTop: 10 }}>
        <TypewriterText key={NOTE} text={NOTE} {...noteSlot} />
      </p>
    </section>
  );
}
